#!/bin/bash
SERIDS=(Arduino_LLC_Arduino_Leonardo Arduino_Srl_Arduino_Leonardo)
    for sysdevpath in $(find /sys/bus/usb/devices/usb*/ -name dev); do
        devname="$(udevadm info -q name -p ${sysdevpath%/dev})"
        [[ "$devname" == "bus/"* ]] && continue
        eval "$(udevadm info -q property --export -p ${sysdevpath%/dev})"
        [[ -z "$ID_SERIAL" ]] && continue
        # try to detect one of multiple serial IDs elements
        for ID in "${SERIDS[@]}" ; do
            TYPE=`echo $ID_SERIAL | grep "$ID"`
            DEVICE=`echo $devname | grep "tty"`
            if [ "$TYPE" != "" ] && [ "$DEVICE" != "" ]; then
                break
            fi
            TYPE=""; DEVICE=""
        done

        [[ -z "$TYPE" ]] && continue
        PORT="/dev/$devname"
        echo "Autodetected serial port is: $PORT"
        break
    done
